console.log(2>1);//true
console.log(2<1);//false
console.log(2>=1);//true
console.log(2<=1);//flase
console.log(2==1);//false
console.log(2!=1);//true
console.log(2==2);//true
console.log(2===2);//true
console.log("2">1);//true
console.log("02">1);//true
